name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            git config --global --add safe.directory /home/ec2-user/new-subhash-website
            cd /home/ec2-user/new-subhash-website
            git pull origin main
            npm install --production
            pm2 restart "my app" || pm2 start server/index.js --name "my app"
